import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    'nav.home': 'Início',
    'nav.listings': 'Jazidas',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'hero.title': 'Oportunidades Premium em Jazidas Minerais',
    'hero.subtitle': 'Conectamos investidores e empresas às melhores reservas minerais do Brasil',
    'hero.cta': 'Explorar Jazidas',
    'hero.search': 'Buscar por mineral, localização...',
    'listings.title': 'Oportunidades Disponíveis',
    'listings.featured': 'Em Destaque',
    'listings.viewAll': 'Ver Todos',
    'listings.viewDetails': 'Ver Detalhes',
    'listings.location': 'Localização',
    'listings.area': 'Área',
    'listings.mineral': 'Mineral',
    'listings.reserves': 'Reservas Estimadas',
    'contact.title': 'Manifeste Seu Interesse',
    'contact.subtitle': 'Preencha o formulário e entraremos em contato',
    'contact.name': 'Nome Completo',
    'contact.email': 'E-mail',
    'contact.phone': 'Telefone',
    'contact.company': 'Empresa',
    'contact.message': 'Mensagem',
    'contact.submit': 'Enviar Mensagem',
    'contact.success': 'Mensagem enviada com sucesso!',
    'login.title': 'Login',
    'login.subtitle': 'Acesse sua conta',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.submit': 'Entrar',
    'login.loading': 'Entrando...',
    'login.noAccount': 'Não tem uma conta?',
    'login.contactUs': 'Entre em contato',
    'footer.rights': 'Todos os direitos reservados.',
    'details.title': 'Detalhes da Jazida',
    'details.overview': 'Visão Geral',
    'details.specifications': 'Especificações Técnicas',
    'details.geology': 'Geologia',
    'details.infrastructure': 'Infraestrutura',
    'details.documentation': 'Documentação',
    'details.gallery': 'Galeria de Imagens',
    'details.interested': 'Interessado nesta Jazida?',
  },
  en: {
    'nav.home': 'Home',
    'nav.listings': 'Deposits',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'Premium Mineral Deposit Opportunities',
    'hero.subtitle': 'Connecting investors and companies to Brazil\'s finest mineral reserves',
    'hero.cta': 'Explore Deposits',
    'hero.search': 'Search by mineral, location...',
    'listings.title': 'Available Deposits',
    'listings.featured': 'Featured',
    'listings.viewAll': 'View All',
    'listings.viewDetails': 'View Details',
    'listings.location': 'Location',
    'listings.area': 'Area',
    'listings.mineral': 'Mineral',
    'listings.reserves': 'Estimated Reserves',
    'contact.title': 'Express Your Interest',
    'contact.subtitle': 'Fill out the form and we\'ll get in touch',
    'contact.name': 'Full Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.company': 'Company',
    'contact.message': 'Message',
    'contact.submit': 'Send Message',
    'contact.success': 'Message sent successfully!',
    'login.title': 'Login',
    'login.subtitle': 'Access your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.loading': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.contactUs': 'Contact us',
    'footer.rights': 'All rights reserved.',
    'details.title': 'Deposit Details',
    'details.overview': 'Overview',
    'details.specifications': 'Technical Specifications',
    'details.geology': 'Geology',
    'details.infrastructure': 'Infrastructure',
    'details.documentation': 'Documentation',
    'details.gallery': 'Image Gallery',
    'details.interested': 'Interested in this Deposit?',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.listings': 'Yacimientos',
    'nav.about': 'Acerca',
    'nav.contact': 'Contacto',
    'hero.title': 'Oportunidades Premium en Yacimientos Minerales',
    'hero.subtitle': 'Conectamos inversores y empresas con las mejores reservas minerales de Brasil',
    'hero.cta': 'Explorar Yacimientos',
    'hero.search': 'Buscar por mineral, ubicación...',
    'listings.title': 'Yacimientos Disponibles',
    'listings.featured': 'Destacados',
    'listings.viewAll': 'Ver Todos',
    'listings.viewDetails': 'Ver Detalles',
    'listings.location': 'Ubicación',
    'listings.area': 'Área',
    'listings.mineral': 'Mineral',
    'listings.reserves': 'Reservas Estimadas',
    'contact.title': 'Exprese Su Interés',
    'contact.subtitle': 'Complete el formulario y nos pondremos en contacto',
    'contact.name': 'Nombre Completo',
    'contact.email': 'Correo Electrónico',
    'contact.phone': 'Teléfono',
    'contact.company': 'Empresa',
    'contact.message': 'Mensaje',
    'contact.submit': 'Enviar Mensaje',
    'contact.success': '¡Mensaje enviado con éxito!',
    'login.title': 'Iniciar Sesión',
    'login.subtitle': 'Accede a tu cuenta',
    'login.email': 'Correo electrónico',
    'login.password': 'Contraseña',
    'login.submit': 'Entrar',
    'login.loading': 'Entrando...',
    'login.noAccount': '¿No tienes cuenta?',
    'login.contactUs': 'Contáctanos',
    'footer.rights': 'Todos los derechos reservados.',
    'details.title': 'Detalles del Yacimiento',
    'details.overview': 'Resumen',
    'details.specifications': 'Especificaciones Técnicas',
    'details.geology': 'Geología',
    'details.infrastructure': 'Infraestructura',
    'details.documentation': 'Documentación',
    'details.gallery': 'Galería de Imágenes',
    'details.interested': '¿Interesado en este Yacimiento?',
  },
  zh: {
    'nav.home': '首页',
    'nav.listings': '矿床',
    'nav.about': '关于',
    'nav.contact': '联系',
    'hero.title': '优质矿床投资机会',
    'hero.subtitle': '连接投资者与企业，共享巴西最佳矿产储备',
    'hero.cta': '探索矿床',
    'hero.search': '按矿物、位置搜索...',
    'listings.title': '可用矿床',
    'listings.featured': '精选',
    'listings.viewAll': '查看全部',
    'listings.viewDetails': '查看详情',
    'listings.location': '位置',
    'listings.area': '面积',
    'listings.mineral': '矿物',
    'listings.reserves': '预估储量',
    'contact.title': '表达您的兴趣',
    'contact.subtitle': '填写表格，我们将与您联系',
    'contact.name': '全名',
    'contact.email': '电子邮件',
    'contact.phone': '电话',
    'contact.company': '公司',
    'contact.message': '留言',
    'contact.submit': '发送消息',
    'contact.success': '消息发送成功！',
    'login.title': '登录',
    'login.subtitle': '访问您的账户',
    'login.email': '电子邮件',
    'login.password': '密码',
    'login.submit': '登录',
    'login.loading': '登录中...',
    'login.noAccount': '没有账户？',
    'login.contactUs': '联系我们',
    'footer.rights': '版权所有。',
    'details.title': '矿床详情',
    'details.overview': '概览',
    'details.specifications': '技术规格',
    'details.geology': '地质',
    'details.infrastructure': '基础设施',
    'details.documentation': '文档',
    'details.gallery': '图片库',
    'details.interested': '对此矿床感兴趣？',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.pt] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
